=== workInJava/git-repository/notebook/corejava/day13/XML/books_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.example.org/books_1_0"
		xmlns:tns="http://www.example.org/books_1_0" 
		elementFormDefault="qualified">
		
	<element name="books">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<element name="book" type="tns:bookType"></element>
			</sequence>
		</complexType>
	</element>
	
	<complexType name="bookType">
		<sequence>
			<element name="isbn" type="string" minOccurs="1"  maxOccurs="1"></element>
			<element name="name" type="string"  minOccurs="1"  maxOccurs="1"></element>
			<element name="author" type="string" minOccurs="1"  maxOccurs="1"></element>
			<element name="bookinfo" type="tns:bookInfoType"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>
	
	<complexType name="bookInfoType">
		<sequence>
			<element name="prices" type="double"></element>
			<element name="pages" type="int"></element>
			<element name="publish_house" type="string"></element>
			<element name="publish_date" type="date"></element>
		</sequence>
	</complexType>
	
</schema>

=== workInJava/git-repository/notebook/corejava/day13/XML/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="http://www.example.org/books_1_0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/books_1_0 books_1_0.xsd ">
	<!-- 注释 -->
	<book id="1">
		<isbn>692587494152</isbn>
		<name>蛙</name>
		<author>莫言</author>
		<bookinfo>
			<prices>24.5</prices>
			<pages>385</pages>
			<publish_house>人文出版社</publish_house>
			<publish_date>2005-11-21</publish_date>
		</bookinfo>
	</book>
	<book id="1">
		<isbn>692587494152</isbn>
		<name>蛙</name>
		<author>莫言</author>
		<bookinfo>
			<prices>24.5</prices>
			<pages>385</pages>
			<publish_house>人文出版社</publish_house>
			<publish_date>2005-11-21</publish_date>
		</bookinfo>
	</book>
</books>
